name: Prepare build environment (Linux only)
description: Set up Java, Maven, Gradle, etc.
runs:
  using: "composite"
  steps: 
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1.0.4
