name: Build toolchain

on:
  workflow_call:
    inputs:
      nightly:
        required: false
        type: boolean
        default: false
      upload-artifacts:
        type: boolean
        required: false
        default: true
      lingua-franca-ref:
        type: string
        required: false
    secrets:
      gpg-passphrase:
        required: false
      gpg-key:
        required: false

  workflow_dispatch:
    inputs:
      upload-artifacts:
        type: boolean
        required: false
        default: true


jobs:
  build-epoch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out epoch repository
        uses: actions/checkout@v3
        with:
          repository: lf-lang/epoch
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:  
          distribution: temurin
          java-version: 17
      - name: Check Maven/Java configuration
        run: mvn -version
        shell: bash
      - name: Update `lingua-franca` submodule
        run: |
          cd org.lflang/lingua-franca
          git fetch --all
          git checkout ${{ inputs.lingua-franca-ref }}
          git pull
          git submodule update
        shell: bash
        if: ${{ inputs.lingua-franca-ref != '' }}
      - name: Configure Git for francabot
        uses: lf-lang/lingua-franca/.github/actions/setup-francabot@francabot
        with:
          gpg-key: ${{ secrets.gpg-key }}
          gpg-passphrase: ${{ secrets.gpg-passphrase }}
        if: ${{ inputs.lingua-franca-ref != '' && inputs.nightly == true }}
      - name: Commit to the `latest` branch
        run: |
          git switch latest || git checkout -b latest
          git add org.lflang/lingua-franca
          git status --porcelain | grep . && git commit -m 'Update lingua-franca submodule'
          git push -f --set-upstream origin latest
        shell: bash
        if: ${{ inputs.lingua-franca-ref != '' && inputs.nightly == true }}
      - name: Build and package epoch
        run: mvn -U package
        shell: bash
      - name: Deploy nightly release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: 'nightly'
          prerelease: true
          title: "Epoch Nightly"
          files: |
            org.lflang.rca/target/products/*.tar.gz
            org.lflang.rca/target/products/*.zip
            org.lflang.updatesite/target/*.zip
        if: ${{ inputs.nightly == true }}
      - name: Upload Build Artifact (Linux)
        uses: actions/upload-artifact@v2
        with:
          name: Epoch-Linux
          path: org.lflang.rca/target/products/epoch_ide_*-linux.gtk.x86_64.tar.gz
          if-no-files-found: error
          retention-days: 5
        if: ${{ inputs.nightly == false && (inputs.upload-artifacts == true || github.event.inputs.upload-artifacts == true) }}
      - name: Upload Build Artifact (Mac)
        uses: actions/upload-artifact@v2
        with:
          name: Epoch-Mac
          path: org.lflang.rca/target/products/epoch_ide_*-macosx.cocoa.*.tar.gz
          if-no-files-found: error
          retention-days: 5
        if: ${{ inputs.nightly == false && (inputs.upload-artifacts == true || github.event.inputs.upload-artifacts == true) }}  
      - name: Upload Build Artifact (Windows)
        uses: actions/upload-artifact@v2
        with:
          name: Epoch-Win
          path: org.lflang.rca/target/products/epoch_ide_*-win32.win32.x86_64.zip
          if-no-files-found: error
          retention-days: 5
        if: ${{ inputs.nightly == false && (inputs.upload-artifacts == true || github.event.inputs.upload-artifacts == true) }}
