name: Build toolchain

on:
  workflow_call:
    inputs:
      nightly:
        required: false
        type: boolean
        default: false
    secrets:
      envPAT:
        required: false
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out epoch repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-env
      - name: Check Maven/Java configuration
        run: mvn -version
        shell: bash
      - name: Build and package epoch
        run: mvn -U package
        shell: bash
      - name: Deploy nightly release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.envPAT }}"
          automatic_release_tag: 'nightly'
          prerelease: true
          title: "Epoch Nightly"
          files: |
            org.lflang.rca/target/products/*.tar.gz
            org.lflang.rca/target/products/*.zip
            org.lflang.updatesite/target/*.zip
        if: ${{ inputs.nightly == true }}
      # - name: Upload Build Artifact (Linux)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Epoch-Linux
      #     path: org.lflang.rca/target/products/epoch_ide_*-linux.gtk.x86_64.tar.gz
      #     if-no-files-found: error
      #   if: ${{ inputs.nightly == false }} 
      # - name: Upload Build Artifact (Mac)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Epoch-Mac
      #     path: org.lflang.rca/target/products/epoch_ide_*-macosx.cocoa.x86_64.tar.gz
      #     if-no-files-found: error
      #   if: ${{ inputs.nightly == false }}  
      # - name: Upload Build Artifact (Windows)
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Epoch-Win
      #     path: org.lflang.rca/target/products/epoch_ide_*-win32.win32.x86_64.zip
      #     if-no-files-found: error
      #   if: ${{ inputs.nightly == false }}
