name: Run C/CCpp tests

on:
  workflow_call:
    inputs:
      compiler-ref:
        required: false
        type: string
      runtime-ref:
        required: false
        type: string
      use-cpp:
        required: false
        type: boolean
        default: false

jobs:
  run:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install JDK
        uses: actions/setup-java@v1.4.3
        with:
          # The Java version to make available on the path.
          # Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x). 
          # Early access versions can be specified in the form of e.g. 14-ea, 14.0.0-ea, or 14.0.0-ea.28
          java-version: 11
      - name: Checkout lingua-franca repo
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.compiler-ref }}
      - name: Checkout reactor-c submodule
        uses: actions/checkout@v2
        with:
          repository: lf-lang/reactor-c
          path: org.lflang/src/lib/c/reactor-c
          ref: ${{ inputs.runtime-ref }}
      - name: Install dependencies Ubuntu
        run: sudo apt-get install libprotobuf-c-dev protobuf-c-compiler protobuf-compiler libprotobuf-dev
        if: runner.os == 'Linux'
      - name: Install dependencies OS X
        run: |
          brew install protobuf
          brew install protobuf-c
          brew install coreutils
        if: runner.os == 'macOS'
      - name: Install RTI
        uses: ./.github/actions/install-rti
        if: ${{ runner.os == 'macOS' || runner.os == 'Linux' }}
      - name: Perform tests for C target
        run: |
          ./gradlew test --tests org.lflang.tests.runtime.CTest.*
        if: ${{ !inputs.use-cpp }}
      - name: Perform tests for CCpp target
        run: |
          ./gradlew test --tests org.lflang.tests.runtime.CCppTest.*
        if: ${{ inputs.use-cpp }}