# Main workflow for testing the Lingua Franca compiler.
name: CI

on:
  # Trigger this workflow on push events, but only on master.
  push:
    branches:
      - main
  # Trigger this workflow also on pull_request events, but ignore the 'nightly' branch.
  pull_request:
    branches-ignore:
      - 'nightly'

concurrency:
  group: ci-${{ github.ref }}-${{ github.event_path }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  # Run the Maven build.
  build:
    uses: ./.github/workflows/build.yml

  # Run tests for Eclipse.
  eclipse-tests:
    uses: ./.github/workflows/eclipse-tests.yml
