# Main workflow for testing the Lingua Franca compiler.
name: CI

on:
  # Trigger this workflow on push events, but only on master.
  push:
    branches:
      - main
  # Trigger this workflow also on pull_request events, but ignore the 'nightly' branch.
  pull_request:
    branches-ignore:
      - 'nightly'

jobs:
  # Cancel previous workflow runs.
  cancel:
    uses: lf-lang/epoch/.github/workflows/cancel.yml@main

  # Run the Maven build.
  build:
    uses: lf-lang/epoch/.github/workflows/build.yml@main
    needs: cancel

  # Run tests for Eclipse.
  eclipse-tests:
    uses: lf-lang/epoch/.github/workflows/eclipse-tests.yml@main
    needs: cancel
