name: Eclipse tests

on:
  workflow_call:

jobs:
  run:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out epoch repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Prepare build environment
        uses: lf-lang/lingua-franca/.github/actions/prepare-build-env@master
      - name: Check Maven/Java configuration
        run: mvn -version
        shell: bash
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Run Eclipse tests
        run: mvn -U -P test integration-test
        shell: bash
