name: Extract ref from file

on:
  workflow_call:
    inputs:
      sha1-file:
        description: Name of the sha1 file to extract the ref from
        type: string
        required: false
    outputs:
      ref:
        description: "The extracted ref"
        value: ${{ jobs.run.outputs.ref }}

jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.read.outputs.ref }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Extract ref from ${{ inputs.sha1-file }}
        id: read
        run: echo "::set-output name=ref::$(head -n 1 ${{ inputs.sha1-file }})"
