name: Report the version of the latest release

on:
  workflow_call:
    inputs:
    outputs:
      ref:
        description: "The version of the latest release"
        value: ${{ jobs.run.outputs.version }}
  # Also allow trigging the workflow manually.
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.find.outputs.version }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install semver-tool
        run: |
          wget -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x /usr/local/bin/semver
          semver --version
      - name: Find the last version
        id: find
        run: echo "::set-output name=version::$(.github/scripts/latest-release.sh)"
