name: Nightly build

# Trigger the workflow every day at 5 AM (UTC).
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      gpg-key: ${{ secrets.GPG_PRIVATE_KEY }}
      gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
    with:
      nightly: true
      lingua-franca-ref: master
      
      