name: Nightly build

# Trigger the workflow every day at 5 AM (UTC).
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: lf-lang/epoch/.github/workflows/build.yml@main
    with:
      nightly: true
    secrets:
      envPAT: ${{ secrets.NIGHTLY_BUILD }}
