name: Run Python tests

on:
  workflow_call:
    inputs:
      compiler-ref:
        required: false
        type: string
      reactor-c-ref:
        required: false
        type: string
      reactor-c-py-ref:
        required: false
        type: string

jobs:
  run:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install dependencies Ubuntu
        run: sudo apt-get install libprotobuf-dev protobuf-compiler
        if: ${{ runner.os == 'Linux' }}
      - name: Install dependencies OS X
        run: |
          brew install protobuf
          brew install coreutils
        if: ${{ runner.os == 'macOS' }}
      - name: Install dependencies Windows
        uses: lukka/run-vcpkg@v4
        with:
          vcpkgArguments: protobuf
          vcpkgGitCommitId: 6185aa76504a5025f36754324abf307cc776f3da
          vcpkgDirectory: ${{ github.workspace }}/vcpkg/
          vcpkgTriplet: x64-windows-static
        if: ${{ runner.os == 'Windows' }}
      - name: Install Google API Python Client
        run: pip3 install --upgrade google-api-python-client
      - name: Check out lingua-franca repository
        uses: actions/checkout@v2
        with:
          submodules: true
          ref: ${{ inputs.compiler-ref }}
      - name: Check out reactor-c submodule
        uses: actions/checkout@v2
        with:
          repository: lf-lang/reactor-c
          path: org.lflang/src/lib/c/reactor-c
          ref: ${{ inputs.reactor-c-ref }}
      - name: Check out reactor-c-py submodule
        uses: actions/checkout@v2
        with:
          repository: lf-lang/reactor-c-py
          path: org.lflang/src/lib/py/reactor-c-py
          ref: ${{ inputs.reactor-c-py-ref }}
      - name: Run Python tests
        run: |
          ./gradlew test --tests org.lflang.tests.runtime.PythonTest.*
