on:
  workflow_call:
    inputs:
      runtime-ref:
        required: false
        type: string

jobs:
  setup-env:
    name: Run C tests
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 # NOTE: if this parameter is not used, fetching an alternative runtime fails.
      - name: Use alternative runtime version
        run: |
          pushd org.lflang/src/lib/c/reactor-c
          git fetch --all
          git checkout ${{ inputs.runtime-ref }}
          popd
        if: ${{ inputs.runtime-ref }}
      - uses: lf-lang/lingua-franca/.github/actions/install-jdk.yml@a3532e0649c82a6c01bfa1d8cfee38cb4e190a77
      - name: Install dependencies Ubuntu
        run: sudo apt-get install libprotobuf-c-dev protobuf-c-compiler protobuf-compiler libprotobuf-dev
        if: runner.os == 'Linux'
      - name: Install dependencies OS X
        run: |
          brew install protobuf
          brew install protobuf-c
          brew install coreutils
        if: runner.os == 'macOS'
      - name: Install RTI
        run: |
          cd org.lflang/src/lib/c/reactor-c/core/federated/RTI
          mkdir build
          cd build
          cmake ../
          make
          sudo make install
        if: ${{ runner.os == 'macOS' || runner.os == 'Linux' }}
      - name: Perform tests
        run: |
          ./gradlew test --tests org.lflang.tests.runtime.CTest.*
