name: Serialization tests

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: ros:latest
    steps:
      - name: Install git
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          if ! apt list --installed 2>/dev/null | grep -q "git.*"; then
            apt install -y git
          elif apt list --installed 2>/dev/null | grep -q "git.*"; then
            true
          else
            exit 255
          fi 
          # Install shellcheck
          if ! apt list --installed 2>/dev/null | grep -q ".*shellcheck.*"; then
            apt install -y shellcheck
          elif apt list --installed 2>/dev/null | grep -q ".*shellcheck.*"; then
            true
          else
            exit 255
          fi 
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Check out lingua-franca repository
        uses: actions/checkout@v2
        with:
          repository: lf-lang/lingua-franca
          submodules: true
      - name: Install Protobuf Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y libprotobuf-c-dev protobuf-c-compiler protobuf-compiler libprotobuf-dev
      - name: Run serialization tests;
        run: ./gradlew test --tests org.lflang.tests.serialization.SerializationTest.*
      - name: Report to CodeCov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: org.lflang.tests/build/reports/xml/jacoco
          fail_ci_if_error: false
          verbose: true
        if: ${{ !inputs.runtime-ref }}  # i.e., if this is part of the main repo's CI
