name: Serialization tests

on:
  workflow_call:
    inputs:
      target:
        required: false
        type: string
        default: C
jobs:
  run:
    container:
      image: osrf/ros
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Check out lingual-franca repository
        uses: actions/checkout@v2
        with:
          repository: lf-lang/lingua-franca
          submodules: true
          ref: ${{ inputs.compiler-ref }}
      - name: Check out specific ref of reactor-CPP
        uses: actions/checkout@v2
        with:
          repository: lf-lang/reactor-cpp
          path: org.lflang/src/lib/cpp/reactor-cpp
          ref: ${{ inputs.runtime-ref }}
        if: ${{ inputs.runtime-ref }}
      - name: Install Protobuf Ubuntu
        run: sudo apt-get install libprotobuf-c-dev protobuf-c-compiler protobuf-compiler libprotobuf-dev
        if: ${{ runner.os == 'Linux' }}
      - name: Install Protobuf OS X
        run: |
          brew install protobuf
          brew install protobuf-c
          brew install coreutils
        if: ${{ runner.os == 'macOS' }}
      - name: Run serialization tests;
        run: |
          source /opt/ros/galactic/setup.bash
          ./gradlew test --tests org.lflang.tests.serialization.SerializationTest.*
      - name: Report to CodeCov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: org.lflang.tests/build/reports/xml/jacoco
          fail_ci_if_error: false
          verbose: true
        if: ${{ !inputs.runtime-ref }}  # i.e., if this is part of the main repo's CI
