name: Run unit tests (and compute code coverage)

on:
  workflow_call:

jobs:
  run:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - uses: actions/checkout@v2
      - name: Run compiler tests
        run: |
          ./gradlew test --tests org.lflang.tests.compiler.*
      - name: Report to CodeCov
        uses: codecov/codecov-action@v2.1.0 
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos 
          file: org.lflang.tests/build/reports/xml/jacoco
          fail_ci_if_error: false
          verbose: true
        if: ${{ runner.os == 'Linux' }}
